# Generated by Django 3.1.2 on 2020-10-30 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.post'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.post'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user'),
        ),
        migrations.AlterField(
            model_name='readspost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.post'),
        ),
        migrations.AlterField(
            model_name='readspost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user'),
        ),
    ]
