# Generated by Django 3.1.2 on 2020-12-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_ucourse_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_Post2',
        ),
    ]
