# Generated by Django 3.1.2 on 2020-12-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_course_course_post'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course_post',
            unique_together={('course', 'post')},
        ),
    ]
