# Generated by Django 3.1.2 on 2020-12-25 10:28

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_file3'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=polls.models.User.email_default, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='pas',
            field=models.BinaryField(default=polls.models.User.pass_default),
        ),
    ]
